version: '3.3'

services:
  postgres:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER}
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul

    networks:
      - app-network


networks:
  app-network:
    driver: bridge