swagger: "2.0"
info:
  title: "My API"
  description: "API for my GCP application"
  version: "1.0.0"
host: "www.librarycompany.store"
schemes:
  - "https"
paths:
  /upload/play-excel:
    post:
      operationId: "uploadPlayExcelPost"
      responses:
        '200':
          description: "File uploaded successfully"
  /upload/ping:
    get:
      summary: "Ping the backend server"
      operationId: "pingBackend"
      responses:
        '200':
          description: "Ping response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "pong"
        '400':
          description: "Bad request"
        '500':
          description: "Server error"
